---
- name: Base - install Docker & Python SDK, create traefik network
  hosts: vps
  become: true

  vars:
    docker_install_compose_plugin: true   # let the role add compose v2 plugin if available

  roles:
    - geerlingguy.docker

  tasks:
    - name: Ensure Docker SDK for Python via apt
      ansible.builtin.package:
        name: python3-docker
        state: present
        update_cache: true

    - name: Ensure 'traefik' Docker network exists
      community.docker.docker_network:
        name: traefik
        driver: bridge
        state: present
