---
- name: Security - UFW and fail2ban
  hosts: vps
  become: true

  tasks:
    - name: Install UFW and fail2ban
      ansible.builtin.package:
        name:
          - ufw
          - fail2ban
        state: present
        update_cache: true

    - name: UFW allow SSH (22), HTTP (80), HTTPS (443)
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: [ "22", "80", "443" ]

    - name: Set UFW default policies (deny incoming, allow outgoing)
      community.general.ufw:
        state: enabled
        policy: "{{ item.policy }}"
        direction: "{{ item.direction }}"
      loop:
        - { policy: deny,  direction: incoming }
        - { policy: allow, direction: outgoing }

    - name: Configure fail2ban for sshd (with UFW banaction)
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.d/sshd.local
        mode: "0644"
        content: |
          [sshd]
          enabled = true
          banaction = ufw
          maxretry = 5
          findtime = 10m
          bantime  = 1h
      notify: Restart fail2ban

  handlers:
    - name: Restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
        enabled: true
