- name: PrivateBin service
  hosts: vps
  become: true

  tasks:
    - name: Create PrivateBin dirs
      ansible.builtin.file:
        path: "{{ privatebin_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure PrivateBin named volume (for data) exists
      community.docker.docker_volume:
        name: privatebin_data
        state: present

    - name: Run PrivateBin
      community.docker.docker_container:
        name: privatebin
        image: "{{ privatebin_image }}"
        restart_policy: unless-stopped
        networks:
          - name: traefik
        volumes:
          - privatebin_data:/srv/data
        labels:
          labels:
          traefik.enable: "true"

          # OPEN: allow viewing & static assets (no auth)
          traefik.http.routers.privatebin-open.rule: "Host(`{{ privatebin_domain }}`) && (Method(`GET`) || Method(`HEAD`))"
          traefik.http.routers.privatebin-open.entrypoints: "websecure"
          traefik.http.routers.privatebin-open.tls.certresolver: "le"

          # WRITE: require BasicAuth for creating/deleting/comments (POST/DELETE)
          traefik.http.routers.privatebin-post.rule: "Host(`{{ privatebin_domain }}`) && (Method(`POST`) || Method(`DELETE`))"
          traefik.http.routers.privatebin-post.entrypoints: "websecure"
          traefik.http.routers.privatebin-post.tls.certresolver: "le"
          traefik.http.routers.privatebin-post.middlewares: "privatebin-auth"

          # Service
          traefik.http.services.privatebin.loadbalancer.server.port: "8080"

          # BasicAuth middleware (Traefik side)
          traefik.http.middlewares.privatebin-auth.basicauth.usersfile: "/auth/usersfile"
          traefik.http.middlewares.privatebin-auth.basicauth.realm: "PrivateBin write access"
 